/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author malsh
 */
public class Database_UI extends javax.swing.JFrame {

    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Database_UI
     * 
     */
//    private javax.swing.JButton insert;
//    private javax.swing.JLabel tDnum;
//    private javax.swing.JLabel tDnumber;
//    private javax.swing.JLabel tMgr_ssn;
//    private javax.swing.JLabel tMgr_start_date;
    
    public Database_UI() {
        initComponents();
        table_update();
        table2_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lDname = new javax.swing.JLabel();
        lDnumber = new javax.swing.JLabel();
        lMgr_ssn = new javax.swing.JLabel();
        lMgr_start_date = new javax.swing.JLabel();
        tDname = new javax.swing.JTextField();
        tDnumber = new javax.swing.JTextField();
        tMgr_start_date = new javax.swing.JTextField();
        tMgr_ssn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lDnum = new javax.swing.JLabel();
        tDnum = new javax.swing.JTextField();
        lDlocation = new javax.swing.JLabel();
        tDlocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Dname");

        jLabel7.setText("Dnumber");

        jLabel8.setText("Mgr_ssn");

        jLabel9.setText("Mgr_start_date");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton4.setText("INSERT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setText("DEPARTMENT");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton6))
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(jTextField7)
                                        .addGap(17, 17, 17))))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(jTextField6)))
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lDname.setText("Dname");

        lDnumber.setText("Dnumber");

        lMgr_ssn.setText("Mgr_ssn");

        lMgr_start_date.setText("Mgr_start_date");

        tDnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDnumberActionPerformed(evt);
            }
        });

        tMgr_ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMgr_ssnActionPerformed(evt);
            }
        });

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("DEPARTMENT");

        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton9.setText("DELETE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setText("DEPARTMENT LOCATION");

        lDnum.setText("Dnumber");

        lDlocation.setText("Dlocation");

        tDlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDlocationActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dname", "Dnumber", "Mgr_ssn", "Mgr_start_date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dnumber", "Dlocation"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lMgr_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tMgr_start_date))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lDname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tDname)
                                                .addComponent(tDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(tMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(update)
                                .addGap(39, 39, 39)
                                .addComponent(jButton9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tDnum)
                                    .addComponent(tDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)
                                .addComponent(jButton3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDname)
                            .addComponent(tDname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDnumber)
                            .addComponent(tDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lMgr_ssn)
                                    .addComponent(tMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(lMgr_start_date))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(tMgr_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert)
                            .addComponent(update)
                            .addComponent(jButton9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDnum)
                            .addComponent(tDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDlocation)
                            .addComponent(tDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    Integer Dnum=Integer.parseInt(tDnum.getText ());
    String Dlocation=tDlocation.getText();
    Connection c = db.getConnection();

    try {
        pst =c.prepareStatement("insert into dept_locations (Dnumber, Dlocation) values (?, ?)");
        pst.setInt (1, Dnum);
        pst.setString(2, Dlocation) ;

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Record added");
        tDnum. setText ("");
        tDlocation.setText ("");

        tDname.requestFocus ();
        table2_update();

    }
    catch (SQLException ex) {
             Logger. getLogger(JavaApplication1. class. getName ()) .log (Level. SEVERE, null, ex) ;
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    Integer Dnumber=Integer.parseInt(tDnum.getText());
    String Dlocation=tDlocation.getText();        
    Connection c = db.getConnection();    
    try {
        pst=c.prepareStatement ("update dept_locations set Dlocation= ? where Dnumber= ?");
        pst.setString(1, Dlocation);
        pst.setInt (2, Dnumber);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Record Updated");
        tDnum.setText ("");
        tDlocation.setText ("");
        tDnum. requestFocus ();
        table2_update();
        }

catch (SQLException ex) {
     Logger. getLogger(JavaApplication1. class.getName()) .log (Level. SEVERE, null, ex) ;
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       Integer Dnumber=Integer.parseInt(tDnum.getText ());
       String Dlocation = tDlocation.getText();
       Connection c = db.getConnection();
    try {
        // Check if there are related entries in department table
        
        pst = c.prepareStatement ("delete from dept_location where Dnumber= ? AND Dlocation = ?") ;
        pst.setInt(1,Dnumber) ;
        pst.setString(2,Dlocation) ;
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Record Deleted");
        tDnum.setText("");
        tDlocation.setText("");
        table2_update();
}
catch (SQLException ex) {
    Logger.getLogger(JavaApplication1.class.getName ()) .log (Level. SEVERE, null, ex);
    }                   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        
        Connection c = db.getConnection();
        
        try {
            String Dname=tDname.getText ();
            Integer Dnumber=Integer.parseInt(tDnumber.getText());
            Integer Mgr_ssn=Integer.parseInt(tMgr_ssn.getText ());
            String Mgr_start_date=tMgr_start_date.getText();
            System.out.println (Dnumber) ;
            
            pst= c.prepareStatement ("insert into department (Dname, Dnumber, Mgr_ssn, Mgr_start_date) value(?,?,?,?)");
            pst.setString(1,Dname);
            pst.setInt(2,Dnumber);
            pst.setInt(3,Mgr_ssn);
            pst.setString(4,Mgr_start_date);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record added");
            tDname.setText ("");
            tDnumber.setText ("");
            tMgr_ssn.setText ("");
            tMgr_start_date.setText("");

            tDname. requestFocus () ;
            table_update(); 
        }

       catch (SQLException ex) {
             Logger.getLogger(JavaApplication1. class. getName ()) .log (Level. SEVERE, null, ex) ;
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection c = db.getConnection();
        
        try {
            String Dname=tDname.getText();
            Integer Dnumber=Integer.parseInt (tDnumber.getText ());
            Integer Mgr_ssn=Integer.parseInt (tMgr_ssn.getText ());
            String Mgr_start_date=tMgr_start_date.getText();
            System.out.println (Dnumber) ;
            
            pst=c.prepareStatement ("update department set Dname= ?, Mgr_ssn= ?, Mgr_start_date= ? where Dnumber= ?");
            pst.setString(1,Dname) ;
            pst.setInt(2, Mgr_ssn) ;
            pst.setString(3,Mgr_start_date);
            pst.setInt (4, Dnumber);
            pst.executeUpdate();
            JOptionPane. showMessageDialog(this, "Record Updated");
            tDname. setText ("");
            tDnumber.setText ("");
            tMgr_ssn.setText ("");
            tMgr_start_date.setText("");
            tDname.requestFocus () ;
            table_update();
        }
        catch (SQLException ex) {
            Logger. getLogger(JavaApplication1. class.getName ()).log (Level.SEVERE, null, ex) ;
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       Integer Dnumber=Integer.parseInt(tDnumber.getText());
       Connection c = db.getConnection();
       try {
        PreparedStatement deleteDeptLocStmt = c.prepareStatement("DELETE FROM dept_locations WHERE Dnumber = ?");
        deleteDeptLocStmt.setInt(1, Dnumber);
        deleteDeptLocStmt.executeUpdate();
   
        pst = c.prepareStatement ("delete from department where Dnumber= ?") ;
        pst.setInt(1,Dnumber) ;
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Record Deleted");
        tDname.setText ("") ;
        tDnumber.setText ("");
        tMgr_ssn.setText ("");
        tMgr_start_date.setText("");

        table_update();
        table2_update();
       }
catch (SQLException ex) {
    Logger.getLogger(JavaApplication1.class.getName ()) .log (Level. SEVERE, null, ex);
    }//GEN-LAST:event_jButton9ActionPerformed
}
    private void tDlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDlocationActionPerformed

    private void tMgr_ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMgr_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMgr_ssnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft=(DefaultTableModel) jTable1.getModel ();
        int selectedIndex=jTable1.getSelectedRow ();

        tDname.setText (dft. getValueAt (selectedIndex, 0).toString());
        tDnumber.setText (dft.getValueAt (selectedIndex, 1).toString());
        tMgr_ssn.setText (dft.getValueAt (selectedIndex, 2).toString());
        tMgr_start_date.setText (dft. getValueAt (selectedIndex, 3).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft=(DefaultTableModel) jTable2.getModel ();
        int selectedIndex=jTable2.getSelectedRow ();

        //tDname.setText (dft. getValueAt (selectedIndex, 0).toString());
        tDnum.setText (dft.getValueAt (selectedIndex, 0).toString());
       // tMgr_ssn.setText (dft.getValueAt (selectedIndex, 2).toString());
        tDlocation.setText (dft. getValueAt (selectedIndex, 1).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Database_UI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lDlocation;
    private javax.swing.JLabel lDname;
    private javax.swing.JLabel lDnum;
    private javax.swing.JLabel lDnumber;
    private javax.swing.JLabel lMgr_ssn;
    private javax.swing.JLabel lMgr_start_date;
    private javax.swing.JTextField tDlocation;
    private javax.swing.JTextField tDname;
    private javax.swing.JTextField tDnum;
    private javax.swing.JTextField tDnumber;
    private javax.swing.JTextField tMgr_ssn;
    private javax.swing.JTextField tMgr_start_date;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void table_update() {
        int count;
        Connection c = db.getConnection();
        
        try {
            pst = c.prepareStatement ("select * from DEPARTMENT");
            rs = pst.executeQuery();
            ResultSetMetaData rsmd =rs.getMetaData();
            count=rsmd.getColumnCount() ;
            DefaultTableModel dft=(DefaultTableModel)jTable1.getModel ();
            dft.setRowCount (0) ;
            while (rs.next () ) {
            Vector v2=new Vector ();
            for(int i=1;i<count; i++) {
            v2.add(rs.getString ("Dname")) ;
            v2.add(rs.getInt("Dnumber")) ;
            v2.add(rs.getInt ("Mgr_ssn"));
            v2.add(rs.getString("Mgr_start_date"));
            }
            dft.addRow(v2);
            }
        }
        catch (SQLException ex) {
             Logger. getLogger(JavaApplication1. class. getName ()) .log (Level. SEVERE, null, ex) ;
        }
  
    }

    private void table2_update() {
        int count;
        Connection c = db.getConnection();
      
        try {

            pst=c.prepareStatement ("select * from DEPT_LOCATIONS");

            rs=pst.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
            count=rsmd.getColumnCount() ;
            DefaultTableModel dft=(DefaultTableModel) jTable2.getModel ();
            dft.setRowCount (0);
            while (rs.next()){
            Vector v2=new Vector ();
            for(int i=1;i<count;i++) {
            v2.add(rs.getInt ("Dnumber")) ;
            v2.add(rs.getString("Dlocation")) ;
            }
            dft.addRow(v2);
            }
        }

    catch (SQLException ex) {
        Logger. getLogger(JavaApplication1.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
}